using System.Collections.Generic;

// Generated by http://json2csharp.com/ using GameWorld.js
public class EvilAction
{
    public string ActionType { get; set; }
    public string Identifier { get; set; }
    public int Peaks { get; set; }
    public int Decibel { get; set; }
    public string ObjectOfInterest { get; set; }
    public string PlacementTarget { get; set; }
    public string details { get; set; }
}

public class TherapyStory
{
    public string DialogeType { get; set; }
    public string Actor { get; set; }
    public string Message { get; set; }
    public string ActionType { get; set; }
}

public class ReviewStory
{
    public string DialogType { get; set; }
    public string Actor { get; set; }
    public string Message { get; set; }
    public string ActionType { get; set; }
    public string Identifier { get; set; }
    public string SolvedMessage { get; set; }
    public string FailedMessage { get; set; }
}

public class Person
{
    public string Name { get; set; }
    public string Alias { get; set; }
    public int Age { get; set; }
    public bool Finished { get; set; }
    public bool Unlocked { get; set; }
    public string SpritePathInResources { get; set; }
    public List<EvilAction> EvilAction { get; set; }
    public List<EvilAction> SolvedActions { get; set; }
    public List<TherapyStory> TherapyStory { get; set; }
    public List<ReviewStory> ReviewStory { get; set; }
}

public class World
{
    public string WorldName { get; set; }
    public List<Person> Persons { get; set; }
}

public class RootObject
{
    public string Game { get; set; }
    public int Revision { get; set; }
    public List<World> Worlds { get; set; }
}